# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /app/frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container
#COPY package*.json ./

# Copy all files from the frontend directory to the container
COPY . /app/frontend

# Install frontend dependencies
RUN npm install

# Expose port 3000 for the React app
EXPOSE 3000

# Run the React development server
CMD ["npm", "start"]

