# Generated by Django 4.2.7 on 2023-12-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oocc', '0002_eventlog_delete_oceleventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='processed_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
