# Generated by Django 4.2.7 on 2023-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oocc', '0003_eventlog_processed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
